name: Main workflow

on:
  pull_request:
  push:
      branches:
        - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

env:
  OPAMYES: 1
  OVERVERBOSE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout opam flambda2 repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: 'flambda2-opam-repo'

      - name: Checkout main opam repository repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: 'ocaml/opam-repository'
          path: 'main-opam-repo'

      - name: Install opam
        run: sudo apt-get update && sudo apt-get install -y opam
      - name: Initialise opam
        run: opam init -ayn --disable-sandboxing --bare ./main-opam-repo
      - name: Install flambda2 compiler
        run: opam switch create -v flambda2 --repositories=default,fl2=flambda2-opam-repo 5.1.1+flambda2
      - name: Install packages
        run: opam install -y `cat flambda2-opam-repo/packages.txt`
