name: Main workflow

on:
  pull_request:
  push:
      branches:
        - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

env:
  OPAMYES: 1
  OVERVERBOSE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout opam flambda2 repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: 'flambda2-opam-repo'

      - name: Checkout main opam repository repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: 'ocaml/opam-repository'
          path: 'main-opam-repo'

      - run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            brew install opam autoconf
          elif [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y opam
          fi
      - run: opam init -ayn --bare ./main-opam-repo
#      - run: opam repo add --set-default fl2 ./flambda2-opam-repo
      - run: opam switch create flambda2 --repositories=default,fl2=flambda2-opam-repo 5.1.1+flambda2
